url: http://www.thisismecoding.com
baseurl: ""

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

exclude:
  - "*.config.js"
  - "package*.json"
  - "assets"
  - "node_modules"

